name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "chaosoffire123432@gmail.com"
          git config --local user.name "Chaos"
          git remote set-url origin https://chaosoffire@github.com/chaosoffire/build.git
          git pull --rebase
          git commit --allow-empty -m "Just a commit"
          git push
