name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "36 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Commit!
        run: |
          git config --local user.email "chaosoffire123432@gmail.com"
          git config --local user.name "Chaos"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Just a commit"
          git push
